# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MBProgressHUD+ZC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'MBProgressHUD'
  # Pods for MBProgressHUD+ZC

  target 'MBProgressHUD+ZCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
